# Generated by Django 5.1 on 2024-08-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='FechaObservacion',
            field=models.DateField(null=True, verbose_name='Fecha observación'),
        ),
    ]
