# Generated by Django 5.1 on 2024-08-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0002_alter_novedades_fechaobservacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='FechaObservacion',
            field=models.DateField(null=True, verbose_name='FechaObservación'),
        ),
    ]
