# Generated by Django 5.1 on 2024-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0005_remove_novedades_coordinador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedades',
            name='coordinador',
        ),
        migrations.RemoveField(
            model_name='novedades',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='novedades',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='novedades',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='novedades',
            name='tecnico',
        ),
        migrations.AlterField(
            model_name='novedades',
            name='fecha_observacion',
            field=models.DateField(null=True, verbose_name='Fecha observación'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='Coordinador',
            field=models.TextField(null=True, verbose_name='Coordinador'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='Descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='Observaciones',
            field=models.TextField(null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='Servicio',
            field=models.TextField(null=True, verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='Tecnico',
            field=models.TextField(null=True, verbose_name='Tecnico'),
        ),
    ]
