# Generated by Django 5.1 on 2024-08-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0006_remove_novedades_coordinador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedades',
            old_name='Coordinador',
            new_name='coordinador',
        ),
        migrations.RenameField(
            model_name='novedades',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='novedades',
            old_name='Observaciones',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='novedades',
            old_name='Servicio',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='novedades',
            old_name='Tecnico',
            new_name='tecnico',
        ),
    ]
