# Generated by Django 5.1 on 2024-08-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0008_alter_novedades_fecha_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caso_cliente', models.TextField(null=True, verbose_name='Observaciones')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('cantidad_equipos', models.TextField(null=True, verbose_name='Coordinador')),
                ('fecha_solicitud', models.DateTimeField(null=True, verbose_name='Fecha observación')),
                ('fecha_programacion', models.DateTimeField(null=True, verbose_name='Fecha observación')),
                ('fecha_cierre', models.DateTimeField(null=True, verbose_name='Fecha observación')),
                ('tiempo_desplazamiento', models.TextField(null=True, verbose_name='Tecnico')),
                ('direccion', models.TextField(null=True, verbose_name='Servicio')),
                ('unidad', models.TextField(null=True, verbose_name='Servicio')),
                ('municipio', models.TextField(null=True, verbose_name='Servicio')),
                ('tipo_servicio', models.TextField(null=True, verbose_name='Servicio')),
                ('cliente', models.TextField(null=True, verbose_name='Servicio')),
            ],
        ),
    ]
