# Generated by Django 5.1 on 2024-08-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0009_asignar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignar',
            name='cantidad_equipos',
            field=models.TextField(null=True, verbose_name='Cantidad Equipos'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='caso_cliente',
            field=models.TextField(null=True, verbose_name='Caso Cliente'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='cliente',
            field=models.TextField(null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='fecha_cierre',
            field=models.DateTimeField(null=True, verbose_name='Fecha Cierre'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='fecha_programacion',
            field=models.DateTimeField(null=True, verbose_name='Fecha Programación'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='fecha_solicitud',
            field=models.DateTimeField(null=True, verbose_name='Fecha Solicitud'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='municipio',
            field=models.TextField(null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='tiempo_desplazamiento',
            field=models.TextField(null=True, verbose_name='Tiempo Desplazamiento'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='tipo_servicio',
            field=models.TextField(null=True, verbose_name='Tipo Servicio'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='unidad',
            field=models.TextField(null=True, verbose_name='Unidad'),
        ),
    ]
