# Generated by Django 5.1 on 2024-08-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0010_alter_asignar_cantidad_equipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar',
            name='glpi',
            field=models.TextField(null=True, verbose_name='GLPI'),
        ),
    ]
