# Generated by Django 5.1 on 2024-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0011_asignar_glpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignar',
            name='cantidad_equipos',
            field=models.IntegerField(null=True, verbose_name='Cantidad Equipos'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='caso_cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Caso Cliente'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='direccion',
            field=models.CharField(max_length=255, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='glpi',
            field=models.CharField(max_length=100, null=True, verbose_name='GLPI'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='municipio',
            field=models.CharField(max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='tiempo_desplazamiento',
            field=models.DurationField(null=True, verbose_name='Tiempo Desplazamiento'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='tipo_servicio',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo Servicio'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='unidad',
            field=models.CharField(max_length=100, null=True, verbose_name='Unidad'),
        ),
    ]
