# Generated by Django 5.1 on 2024-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0013_alter_asignar_cantidad_equipos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='coordinador',
            field=models.CharField(max_length=100, null=True, verbose_name='Coordinador'),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='servicio',
            field=models.CharField(max_length=100, null=True, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='tecnico',
            field=models.CharField(max_length=100, null=True, verbose_name='Técnico'),
        ),
    ]
