# Generated by Django 4.1.3 on 2024-08-29 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0014_alter_novedades_coordinador_alter_novedades_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contratos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField(null=True, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateTimeField(null=True, verbose_name='Fecha Fin')),
                ('tipoContrato', models.TextField(null=True, verbose_name='Tipo de Contrato')),
                ('salario', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Salario')),
                ('fechaPago', models.DateTimeField(null=True, verbose_name='Fecha Pago')),
                ('numCuenta', models.CharField(max_length=100, null=True, verbose_name='Número de Cuenta')),
                ('funcion', models.TextField(null=True, verbose_name='Función')),
                ('cargo', models.TextField(null=True, verbose_name='Cargo')),
                ('estado', models.TextField(null=True, verbose_name='estado')),
                ('numCaso', models.CharField(max_length=100, null=True, verbose_name='Número de Caso')),
                ('horario', models.CharField(max_length=100, null=True, verbose_name='Horaario')),
                ('entidadFinanciera', models.CharField(max_length=100, null=True, verbose_name='Entidad Financiera')),
                ('cliente', models.CharField(max_length=100, null=True, verbose_name='Cliente')),
            ],
        ),
    ]
