# Generated by Django 4.1.3 on 2024-08-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0016_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
