# Generated by Django 4.1.3 on 2024-08-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0017_alter_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('tipo_contrato', models.CharField(max_length=100, verbose_name='Tipo de Contrato')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('numero_cuenta', models.CharField(max_length=20, verbose_name='Número de Cuenta')),
                ('funcion', models.CharField(max_length=100, verbose_name='Función')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('numero_caso', models.CharField(max_length=50, verbose_name='Número de Caso')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('entidad_financiera', models.CharField(max_length=100, verbose_name='Entidad Financiera')),
                ('cliente_empresa', models.CharField(max_length=100, verbose_name='Cliente Empresa')),
                ('aporte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aporte')),
            ],
        ),
    ]
