# Generated by Django 4.1.3 on 2024-08-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0019_clientes_novedades_th_delete_contratos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='novedades',
            new_name='Novedad',
        ),
    ]
