# Generated by Django 4.1.3 on 2024-08-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0020_rename_novedades_novedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresaAporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=100, null=True, verbose_name='Entidad')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('estado', models.CharField(max_length=50, null=True, verbose_name='Estado')),
            ],
        ),
    ]
