# Generated by Django 5.1 on 2024-08-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0021_empresaaporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignar',
            name='fecha_cierre',
            field=models.DateField(null=True, verbose_name='Fecha Cierre'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='fecha_programacion',
            field=models.DateField(null=True, verbose_name='Fecha Programación'),
        ),
        migrations.AlterField(
            model_name='asignar',
            name='fecha_solicitud',
            field=models.DateField(null=True, verbose_name='Fecha Solicitud'),
        ),
    ]
