# Generated by Django 5.1 on 2024-08-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git', '0022_alter_asignar_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='fecha_observacion',
            field=models.DateField(null=True, verbose_name='Fecha observación'),
        ),
        migrations.AlterField(
            model_name='novedades_th',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='Fecha Inicio'),
        ),
    ]
